platform :ios, '8.0'
inhibit_all_warnings!

target 'bujilvxing' do
 
pod 'Masonry', '~> 1.0.0'
pod 'SDAutoLayout', '~> 2.1.1'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~>3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'pop', '~> 1.0.9'
pod 'SDWebImage', '~> 3.8.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'ReactiveCocoa', '~> 2.5'
pod 'JSBadgeView', '~> 1.4.1'
pod 'GJAlertController', '~> 1.0.0'
pod 'JCAlertView', '~> 1.1.5'
pod 'IQKeyboardManager', '~> 4.0.0'
pod 'BaiduMapKit', '~> 3.0.0'
pod 'SDCycleScrollView', '~> 1.65'
end
